github.com:
    users:
        umed9696:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: umed9696
